command:
  - streamlit
  - run
  - demo_streamlit/app.py

env:
  - name: UC_TABLE_NAME
    valueFrom: "ml_prod_dev.ds_team.gold_nbc_test_dataset_with_embeddings"
  
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: "151258857980e19b"